name: 'Create and test Docker image'
description: 'Creates a Docker image from the input parameters. Then tests SQL Server connection using the image.'
inputs:
  source-directory:
    description: 'The source directory relative to the repository root.'
    required: true
  image-tag:
    description: 'The image tag to use for the Docker image.'
    required: true
  dockerhub-username:
    description: 'The DockerHub username to use when pushing the built Docker image.'
    required: true
  dockerhub-password:
    description: 'The DockerHub password to use when pushing the built Docker image.'
    required: true
  tests-sqlsrv-password:
    description: 'The password to for the SQL Server instance to use when testing the Docker image.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup SQL Server 2017
      uses: 280780363/sqlserver-action@v1.0
      with:
        accept eula: 'Y'
        sa password: ${{ inputs.tests-sqlsrv-password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Build namoshek/php-mssql:${{ inputs.image-tag }}
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.source-directory }}
        tags: namoshek/php-mssql:${{ inputs.image-tag }}
        platforms: linux/amd64
        load: true
        
    - name: Test SQL Server connection
      uses: addnab/docker-run-action@v3
      with:
        image: namoshek/php-mssql:${{ inputs.image-tag }}
        options: -v ${{ github.workspace }}/.ci/tests:/work -e MSSQL_HOST=127.0.0.1 -e MSSQL_PORT=1433 -e MSSQL_DATABASE=master -e MSSQL_USERNAME=sa -e MSSQL_PASSWORD=${{ inputs.tests-sqlsrv-password }}
        run: php /work/test_connection.php

    - name: Push namoshek/php-mssql:${{ inputs.image-tag }}
      uses: docker/build-push-action@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        context: ${{ inputs.source-directory }}
        tags: namoshek/php-mssql:${{ inputs.image-tag }}
        platforms: linux/amd64
        push: true
