name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  # PHP 8.1 Alpine Linux with Swoole Extension
  build-8_1-cli-alpine-swoole:
    name: namoshek/php-mssql:8.1-cli-alpine-swoole
    runs-on: ubuntu-latest
    needs: build-8_1-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.1/cli-alpine-swoole
          image-tag: 8.1-cli-alpine-swoole

  build-8_1-fpm-alpine-swoole:
    name: namoshek/php-mssql:8.1-fpm-alpine-swoole
    runs-on: ubuntu-latest
    needs: build-8_1-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.1/fpm-alpine-swoole
          image-tag: 8.1-fpm-alpine-swoole

  # PHP 8.1 Alpine Linux
  build-8_1-cli-alpine:
    name: namoshek/php-mssql:8.1-cli-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.1/cli-alpine
          image-tag: 8.1-cli-alpine

  build-8_1-fpm-alpine:
    name: namoshek/php-mssql:8.1-fpm-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.1/fpm-alpine
          image-tag: 8.1-fpm-alpine

  # PHP 8.1 Debian
  build-8_1-cli:
    name: namoshek/php-mssql:8.1-cli
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.1/cli
          image-tag: 8.1-cli

  build-8_1-fpm:
    name: namoshek/php-mssql:8.1-fpm
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.1/fpm
          image-tag: 8.1-fpm

  # PHP 8.0 Alpine Linux with Swoole Extension
  build-8_0-cli-alpine-swoole:
    name: namoshek/php-mssql:8.0-cli-alpine-swoole
    runs-on: ubuntu-latest
    needs: build-8_0-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.0/cli-alpine-swoole
          image-tag: 8.0-cli-alpine-swoole

  build-8_0-fpm-alpine-swoole:
    name: namoshek/php-mssql:8.0-fpm-alpine-swoole
    runs-on: ubuntu-latest
    needs: build-8_0-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.0/fpm-alpine-swoole
          image-tag: 8.0-fpm-alpine-swoole

  # PHP 8.0 Alpine Linux
  build-8_0-cli-alpine:
    name: namoshek/php-mssql:8.0-cli-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.0/cli-alpine
          image-tag: 8.0-cli-alpine

  build-8_0-fpm-alpine:
    name: namoshek/php-mssql:8.0-fpm-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.0/fpm-alpine
          image-tag: 8.0-fpm-alpine

  # PHP 8.0 Debian
  build-8_0-cli:
    name: namoshek/php-mssql:8.0-cli
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.0/cli
          image-tag: 8.0-cli

  build-8_0-fpm:
    name: namoshek/php-mssql:8.0-fpm
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 8.0/fpm
          image-tag: 8.0-fpm

  # PHP 7.4
  build-7_4-cli:
    name: namoshek/php-mssql:7.4-cli
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 7.4/cli
          image-tag: 7.4-cli

  build-7_4-fpm:
    name: namoshek/php-mssql:7.4-fpm
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 7.4/fpm
          image-tag: 7.4-fpm

  # PHP 7.3          
  build-7_3-cli:
    name: namoshek/php-mssql:7.3-cli
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 7.3/cli
          image-tag: 7.3-cli

  build-7_3-fpm:
    name: namoshek/php-mssql:7.3-fpm
    runs-on: ubuntu-latest
    steps:
      - uses: ./.ci/actions/create-and-test-docker-image
        with:
          source-directory: 7.3/fpm
          image-tag: 7.3-fpm
