name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  # PHP 8.4 Alpine Linux with Swoole Extension
  build-8_4-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.4-cli-alpine-swoole
    needs: build-8_4-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.4/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.4-cli-alpine-swoole

  build-8_4-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.4-fpm-alpine-swoole
    needs: build-8_4-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.4/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.4-fpm-alpine-swoole

  # PHP 8.4 Alpine Linux
  build-8_4-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.4-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.4/cli-alpine
      image-tag: namoshek/php-mssql:8.4-cli-alpine

  build-8_4-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.4-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.4/fpm-alpine
      image-tag: namoshek/php-mssql:8.4-fpm-alpine

  # PHP 8.4 Debian
  build-8_4-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.4-cli
    secrets: inherit
    with:
      source-directory: 8.4/cli
      image-tag: namoshek/php-mssql:8.4-cli

  build-8_4-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.4-fpm
    secrets: inherit
    with:
      source-directory: 8.4/fpm
      image-tag: namoshek/php-mssql:8.4-fpm

  # PHP 8.3 Alpine Linux with Swoole Extension
  build-8_3-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.3-cli-alpine-swoole
    needs: build-8_3-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.3/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.3-cli-alpine-swoole

  build-8_3-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.3-fpm-alpine-swoole
    needs: build-8_3-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.3/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.3-fpm-alpine-swoole

  # PHP 8.3 Alpine Linux
  build-8_3-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.3-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.3/cli-alpine
      image-tag: namoshek/php-mssql:8.3-cli-alpine

  build-8_3-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.3-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.3/fpm-alpine
      image-tag: namoshek/php-mssql:8.3-fpm-alpine

  # PHP 8.3 Debian
  build-8_3-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.3-cli
    secrets: inherit
    with:
      source-directory: 8.3/cli
      image-tag: namoshek/php-mssql:8.3-cli

  build-8_3-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.3-fpm
    secrets: inherit
    with:
      source-directory: 8.3/fpm
      image-tag: namoshek/php-mssql:8.3-fpm

  # PHP 8.2 Alpine Linux with Swoole Extension
  build-8_2-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-cli-alpine-swoole
    needs: build-8_2-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.2/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.2-cli-alpine-swoole

  build-8_2-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-fpm-alpine-swoole
    needs: build-8_2-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.2/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.2-fpm-alpine-swoole

  # PHP 8.2 Alpine Linux
  build-8_2-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.2/cli-alpine
      image-tag: namoshek/php-mssql:8.2-cli-alpine

  build-8_2-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.2/fpm-alpine
      image-tag: namoshek/php-mssql:8.2-fpm-alpine

  # PHP 8.2 Debian
  build-8_2-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-cli
    secrets: inherit
    with:
      source-directory: 8.2/cli
      image-tag: namoshek/php-mssql:8.2-cli

  build-8_2-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-fpm
    secrets: inherit
    with:
      source-directory: 8.2/fpm
      image-tag: namoshek/php-mssql:8.2-fpm

  # PHP 8.1 Alpine Linux with Swoole Extension
  build-8_1-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-cli-alpine-swoole
    needs: build-8_1-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.1/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.1-cli-alpine-swoole

  build-8_1-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-fpm-alpine-swoole
    needs: build-8_1-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.1/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.1-fpm-alpine-swoole

  # PHP 8.1 Alpine Linux
  build-8_1-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.1/cli-alpine
      image-tag: namoshek/php-mssql:8.1-cli-alpine

  build-8_1-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.1/fpm-alpine
      image-tag: namoshek/php-mssql:8.1-fpm-alpine

  # PHP 8.1 Debian
  build-8_1-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-cli
    secrets: inherit
    with:
      source-directory: 8.1/cli
      image-tag: namoshek/php-mssql:8.1-cli

  build-8_1-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-fpm
    secrets: inherit
    with:
      source-directory: 8.1/fpm
      image-tag: namoshek/php-mssql:8.1-fpm
