name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  build-8_0-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 8.0-cli
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 8.0/cli
          tags: "8.0-cli"
          snapshot: true
  build-8_0-fpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 8.0-fpm
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 8.0/fpm
          tags: "8.0-fpm"
          snapshot: true
  build-7_4-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 7.4-cli
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 7.4/cli
          tags: "latest,latest-cli,7.4-cli"
          snapshot: true
  build-7_4-fpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 7.4-fpm
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 7.4/fpm
          tags: "latest-fpm,7.4-fpm"
          snapshot: true
  build-7_3-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 7.3-cli
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 7.3/cli
          tags: "7.3-cli"
  build-7_3-fpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 7.3-fpm
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 7.3/fpm
          tags: "7.3-fpm"
