name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  # START: temporary patch versions
  # PHP 8.2.8 Alpine Linux with Swoole Extension
  build-8_2_8-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2.8-cli-alpine-swoole
    needs: build-8_2_8-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.2.8/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.2.8-cli-alpine-swoole

  build-8_2_8-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2.8-fpm-alpine-swoole
    needs: build-8_2_8-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.2.8/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.2.8-fpm-alpine-swoole

  # PHP 8.2.8 Alpine Linux
  build-8_2_8-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2.8-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.2.8/cli-alpine
      image-tag: namoshek/php-mssql:8.2.8-cli-alpine

  build-8_2_8-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2.8-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.2.8/fpm-alpine
      image-tag: namoshek/php-mssql:8.2.8-fpm-alpine

  # PHP 8.2.8 Debian
  build-8_2_8-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2.8-cli
    secrets: inherit
    with:
      source-directory: 8.2.8/cli
      image-tag: namoshek/php-mssql:8.2.8-cli

  build-8_2_8-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2.8-fpm
    secrets: inherit
    with:
      source-directory: 8.2.8/fpm
      image-tag: namoshek/php-mssql:8.2.8-fpm

  # PHP 8.1.21 Alpine Linux with Swoole Extension
  build-8_1_21-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1.21-cli-alpine-swoole
    needs: build-8_1_21-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.1.21/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.1.21-cli-alpine-swoole

  build-8_1_21-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1.21-fpm-alpine-swoole
    needs: build-8_1_21-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.1.21/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.1.21-fpm-alpine-swoole

  # PHP 8.1.21 Alpine Linux
  build-8_1_21-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1.21-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.1.21/cli-alpine
      image-tag: namoshek/php-mssql:8.1.21-cli-alpine

  build-8_1_21-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1.21-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.1.21/fpm-alpine
      image-tag: namoshek/php-mssql:8.1.21-fpm-alpine

  # PHP 8.1.21 Debian
  build-8_1_21-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1.21-cli
    secrets: inherit
    with:
      source-directory: 8.1.21/cli
      image-tag: namoshek/php-mssql:8.1.21-cli

  build-8_1_21-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1.21-fpm
    secrets: inherit
    with:
      source-directory: 8.1.21/fpm
      image-tag: namoshek/php-mssql:8.1.21-fpm
  # END: temporary patch versions


  # PHP 8.2 Alpine Linux with Swoole Extension
  build-8_2-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-cli-alpine-swoole
    needs: build-8_2-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.2/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.2-cli-alpine-swoole

  build-8_2-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-fpm-alpine-swoole
    needs: build-8_2-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.2/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.2-fpm-alpine-swoole

  # PHP 8.2 Alpine Linux
  build-8_2-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.2/cli-alpine
      image-tag: namoshek/php-mssql:8.2-cli-alpine

  build-8_2-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.2/fpm-alpine
      image-tag: namoshek/php-mssql:8.2-fpm-alpine

  # PHP 8.2 Debian
  build-8_2-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-cli
    secrets: inherit
    with:
      source-directory: 8.2/cli
      image-tag: namoshek/php-mssql:8.2-cli

  build-8_2-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.2-fpm
    secrets: inherit
    with:
      source-directory: 8.2/fpm
      image-tag: namoshek/php-mssql:8.2-fpm

  # PHP 8.1 Alpine Linux with Swoole Extension
  build-8_1-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-cli-alpine-swoole
    needs: build-8_1-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.1/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.1-cli-alpine-swoole

  build-8_1-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-fpm-alpine-swoole
    needs: build-8_1-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.1/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.1-fpm-alpine-swoole

  # PHP 8.1 Alpine Linux
  build-8_1-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.1/cli-alpine
      image-tag: namoshek/php-mssql:8.1-cli-alpine

  build-8_1-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.1/fpm-alpine
      image-tag: namoshek/php-mssql:8.1-fpm-alpine

  # PHP 8.1 Debian
  build-8_1-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-cli
    secrets: inherit
    with:
      source-directory: 8.1/cli
      image-tag: namoshek/php-mssql:8.1-cli

  build-8_1-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.1-fpm
    secrets: inherit
    with:
      source-directory: 8.1/fpm
      image-tag: namoshek/php-mssql:8.1-fpm

  # PHP 8.0 Alpine Linux with Swoole Extension
  build-8_0-cli-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.0-cli-alpine-swoole
    needs: build-8_0-cli-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.0/cli-alpine-swoole
      image-tag: namoshek/php-mssql:8.0-cli-alpine-swoole

  build-8_0-fpm-alpine-swoole:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.0-fpm-alpine-swoole
    needs: build-8_0-fpm-alpine
    if: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
    with:
      source-directory: 8.0/fpm-alpine-swoole
      image-tag: namoshek/php-mssql:8.0-fpm-alpine-swoole

  # PHP 8.0 Alpine Linux
  build-8_0-cli-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.0-cli-alpine
    secrets: inherit
    with:
      source-directory: 8.0/cli-alpine
      image-tag: namoshek/php-mssql:8.0-cli-alpine

  build-8_0-fpm-alpine:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.0-fpm-alpine
    secrets: inherit
    with:
      source-directory: 8.0/fpm-alpine
      image-tag: namoshek/php-mssql:8.0-fpm-alpine

  # PHP 8.0 Debian
  build-8_0-cli:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.0-cli
    secrets: inherit
    with:
      source-directory: 8.0/cli
      image-tag: namoshek/php-mssql:8.0-cli

  build-8_0-fpm:
    uses: ./.github/workflows/create-and-test-docker-image.yml
    name: namoshek/php-mssql:8.0-fpm
    secrets: inherit
    with:
      source-directory: 8.0/fpm
      image-tag: namoshek/php-mssql:8.0-fpm
