name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  # PHP 8.0 Alpine Linux with Swoole Extension
  build-8_0-cli-alpine-swoole:
    name: namoshek/php-mssql:8.0-cli-alpine-swoole
    runs-on: ubuntu-latest
    needs: build-8_0-cli-alpine
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 8.0-cli-alpine-swoole
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 8.0/cli-alpine-swoole
          tags: "8.0-cli-alpine-swoole"
          snapshot: true

  build-8_0-fpm-alpine-swoole:
    name: namoshek/php-mssql:8.0-fpm-alpine-swoole
    runs-on: ubuntu-latest
    needs: build-8_0-fpm-alpine
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 8.0-fpm-alpine-swoole
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 8.0/fpm-alpine-swoole
          tags: "8.0-fpm-alpine-swoole"
          snapshot: true

  # PHP 8.0 Alpine Linux
  build-8_0-cli-alpine:
    name: namoshek/php-mssql:8.0-cli-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 8.0-cli-alpine
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 8.0/cli-alpine
          tags: "8.0-cli-alpine"
          snapshot: true

  build-8_0-fpm-alpine:
    name: namoshek/php-mssql:8.0-fpm-alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 8.0-fpm-alpine
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 8.0/fpm-alpine
          tags: "8.0-fpm-alpine"
          snapshot: true

  # PHP 8.0 Debian
  build-8_0-cli:
    name: namoshek/php-mssql:8.0-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 8.0-cli
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 8.0/cli
          tags: "8.0-cli"
          snapshot: true

  build-8_0-fpm:
    name: namoshek/php-mssql:8.0-fpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 8.0-fpm
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 8.0/fpm
          tags: "8.0-fpm"
          snapshot: true

  # PHP 7.4
  build-7_4-cli:
    name: namoshek/php-mssql:7.4-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 7.4-cli
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 7.4/cli
          tags: "7.4-cli"
          snapshot: true

  build-7_4-fpm:
    name: namoshek/php-mssql:7.4-fpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 7.4-fpm
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 7.4/fpm
          tags: "7.4-fpm"
          snapshot: true

  # PHP 7.3          
  build-7_3-cli:
    name: namoshek/php-mssql:7.3-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 7.3-cli
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 7.3/cli
          tags: "7.3-cli"

  build-7_3-fpm:
    name: namoshek/php-mssql:7.3-fpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish 7.3-fpm
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: namoshek/php-mssql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: 7.3/fpm
          tags: "7.3-fpm"
